version: "3"
services:

  web:
    build: ./devenv/web
    stdin_open: true
    container_name: web
    volumes:
      - ./front-end:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  app:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./devenv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./back-end/public:/app/public:cached
    depends_on:
      - php

  php:
    build: ./devenv/php/
    volumes:
      - ./back-end:/app:cached
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
